### ISSUE TITLE
plugin doesn't work because of bitbucket updated their API

### ISSUE THREAD

**Issue by yosi-yaffe-alcd** [mallowlabs/bitbucket-oauth-plugin#13]
bitbucket api v1.0 isn't available anymore
look in : bitbucket-oauth-plugin/src/main/java/org/jenkinsci/plugins/api/BitbucketApi.java

the endpoint url is : OAUTH_ENDPOINT = "https://bitbucket.org/api/1.0/oauth/";

also : bitbucket-oauth-plugin/src/main/java/org/jenkinsci/plugins/api/BitbucketApiService.java
private static final String API2_ENDPOINT = "https://api.bitbucket.org/2.0/";

in both bitbucket return that this references doesn't exist anymore
{
"type": "error",
"error": {
"message": "Resource not found",
"detail": "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"
}
}

pls update the api for the new format : https://developer.atlassian.com/cloud/bitbucket/oauth-2/

**Comment by mallowlabs** [comment]
It works for me.

Bitbucket API 1.0 and 2.0 works fine, Bitbucket OAuth 1.0 and 2.0 also works fine.
If you access these ENDPOINT URLs directory, you may be confused.

Could you read the document https://wiki.jenkins.io/display/JENKINS/Bitbucket+OAuth+Plugin ?

Check `Setup` section.

**Comment by chrisLeeTW** [comment]
actually all bitbucket 1.0 APIs will be removed from the REST API permanently on 31 December 2018.  (https://confluence.atlassian.com/bitbucket/version-1-423626337.html) 

so refactoring is necessary.

**Comment by chrisLeeTW** [comment]
hope this PR will be helpful. (https://github.com/mallowlabs/bitbucket-oauth-plugin/pull/16)

**Comment by mallowlabs** [comment]
bitbucket-oauth-plugin v0.8 supports Bitbucket API 2 and OAuth 2.0 now.
Please check it.
