### ISSUE TITLE
OAuth Security Token saved in plaintext

### ISSUE THREAD

**Issue by jrnt30** [mallowlabs/bitbucket-oauth-plugin#17]
Currently the configuration for the OAuth token is shown in the form as plaintext.  Further, I found the help text "Registered OAuth application ID/Secret will be visible only for user who created it." to be slightly misleading and head read it as "The Secret will only be visible in *Jenkins* to the user who created it".

I understand the permissions are somewhat limited, but what are your thoughts on changing this to a password field anyways?

**Comment by mallowlabs** [comment]
I think password field is better.
bitbucket-oauth-plugin v0.8 changed the field to password.
Please check it.
