### ISSUE TITLE
Feature Request: Support groups/teams

### ISSUE THREAD

**Issue by micw** [mallowlabs/bitbucket-oauth-plugin#6]
Hi,

it would be great, if teams and groups could be supported. It shouldn't be a big deal. The REST-Api under user/privileges/ shows a list of the user's teams and the user's permission group within the team. Example:

{
  "teams":  {
    "team-test1": "admin",
    "team-test2": "collaborator"
  }
}

To allow flexible permission management, multiple groups for jenkins should be created from the above:

A group for each Team+Permission
team-test1_admin
team-test2_collaborator

A group for each Team.
TEAM_team-test1
TEAM_team-test2

A group for each Permission.
GRP_admin
GRP_collaborator

This allows to give jenkins rights to all members of a team, to all admins or to all collaborators of a certain team.

**Comment by plentz** [comment]
@micw is that possible already?

**Comment by dragolabs** [comment]
same question =)

**Comment by mallowlabs** [comment]
Added Bitbucket team based access control at v6.0.

https://wiki.jenkins.io/display/JENKINS/Bitbucket+OAuth+Plugin#BitbucketOAuthPlugin-BitbucketTeamaccessSupport
