### ISSUE TITLE
Plug-in requests read write access

### ISSUE THREAD

**Issue by kylecordes** [mallowlabs/bitbucket-oauth-plugin#7]
Unfortunately at the moment the JIRA tracker for Jenkins appears to be broken; as I understand the convention is to put issues for Jenkins plug-ins there rather than in projects separate issue trackers.

Here is the issue. This plug-in appears to request full read/write access to the users BitBucket repositories. As far as I can tell, it does not actually need such access or use it; it uses BitBucket only as a source of identity. The message requesting full read/write access is therefore needlessly scary to end-users.

Can it be made to request and prompt only for identity and not for read/write access?

From reading the source of this plug-in, I do not see anywhere that it is explicitly requesting higher level; so it is possible that this is just a limitation and how BitBucket works. If so, it would be good to document that on the plugin description page.

**Comment by mallowlabs** [comment]
The reason is that this plugin used Bitbucket API *1.0*.
The `user` API 1.0 needs repository read permission in actually.

I released Bitbucket OAuth Plugin `v0.6`.
The version uses Bitbucket API *2.0*, So you need only *Account Read* permission.
Please try it.
